# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcalcCaseInsensitive():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    # Wait until the page has loaded
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.TAG_NAME, "body"))
    )
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcalcCaseInsensitive(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.find_element(By.LINK_TEXT, "Tuition Calculator").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    self.driver.find_element(By.ID, "uni-search-0").send_keys("exampleuni")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".uni-results > .result-item")))
    self.driver.find_element(By.CSS_SELECTOR, ".result-item").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    element = self.driver.find_element(By.ID, "uni-search-0")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "uni-search-0").send_keys("EXAMPLEUNI")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".result-item")))
    self.driver.find_element(By.CSS_SELECTOR, ".result-item").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    element = self.driver.find_element(By.ID, "uni-search-0")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "uni-search-0").send_keys("ExampleUni")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".result-item")))
    self.driver.find_element(By.CSS_SELECTOR, ".result-item").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    element = self.driver.find_element(By.ID, "uni-search-0")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "uni-search-0").send_keys("ExaMpLe UnI")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".result-item")))
    self.driver.find_element(By.CSS_SELECTOR, ".result-item").click()
  
