# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCalcsaveAndLoad():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    # Wait until the page has loaded
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.TAG_NAME, "body"))
    )
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_calcsaveAndLoad(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("testuser")
    self.driver.find_element(By.ID, "id_password").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Tuition Calculator").click()
    self.driver.find_element(By.ID, "uni-search-0").click()
    self.driver.find_element(By.ID, "uni-search-0").send_keys("MarsU")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".result-item")))
    self.driver.find_element(By.XPATH, "//div[contains(@class, \'result-item\')]/strong[contains(text(), \'MarsU\')]").click()
    self.driver.find_element(By.ID, "dept-dropdown-0").click()
    dropdown = self.driver.find_element(By.ID, "dept-dropdown-0")
    dropdown.find_element(By.XPATH, "//option[. = 'Agriculture and Environmental Studies']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(9)").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".result-item")))
    self.driver.find_element(By.CSS_SELECTOR, "strong").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "custom-aid-0")))
    self.driver.find_element(By.ID, "custom-aid-0").click()
    self.driver.find_element(By.ID, "custom-aid-0").send_keys("5000")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#panel-closed .right-align").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#entry-0 .save")))
    self.driver.find_element(By.CSS_SELECTOR, "#entry-0 .save").click()
    self.driver.find_element(By.CSS_SELECTOR, "#entry-0 .remove").click()
    self.driver.find_element(By.ID, "loadCalc").click()
    self.driver.find_element(By.ID, "loadCalc").click()
    self.driver.find_element(By.ID, "loadCalc").send_keys("MarsU")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(@class, \'result-item\')]/strong[contains(text(), \'MarsU\')]")))
    self.driver.find_element(By.XPATH, "//div[contains(@class, \'result-item\')]/strong[contains(text(), \'MarsU\')]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fake-link:nth-child(5)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#entry-0 .delete-save").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout-button").click()
  
