# Generated by Django 5.1.3 on 2025-04-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
