# Generated by Django 4.2.16 on 2024-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('prospective_student', 'Prospective Student'), ('current_student', 'Current Student'), ('alumni', 'Alumni'), ('university_staff', 'University Staff'), ('admin', 'Admin')], default='prospective_student', max_length=20),
        ),
    ]
