# Generated by Django 4.2.16 on 2024-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
