# Generated by Django 5.1.3 on 2024-11-27 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
