# Generated by Django 5.1.3 on 2024-12-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0006_major_fees_university_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
