# Generated by Django 5.1.3 on 2024-12-04 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0007_financialaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorreview',
            name='university',
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='review_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
