# Generated by Django 5.1.3 on 2024-12-04 22:30

import MajorHelp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0008_remove_majorreview_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorreview',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MajorHelp.university'),
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='review_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='majorreview',
            name='user',
            field=models.ForeignKey(default=MajorHelp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
