# Generated by Django 5.1.3 on 2024-12-05 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0009_majorreview_university_alter_majorreview_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_courses', to='MajorHelp.major')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='majors', to='MajorHelp.course'),
        ),
    ]
