# Generated by Django 5.1.3 on 2024-12-05 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0010_course_major_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='grad_in_state_max_tuition',
            field=models.IntegerField(default=0, help_text='Maximum in-state tuition for graduate students.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='grad_in_state_min_tuition',
            field=models.IntegerField(default=0, help_text='Minimum in-state tuition for graduate students.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='grad_out_of_state_max_tuition',
            field=models.IntegerField(default=0, help_text='Maximum out-of-state tuition for graduate students.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='grad_out_of_state_min_tuition',
            field=models.IntegerField(default=0, help_text='Minimum out-of-state tuition for graduate students.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
