# Generated by Django 4.2.16 on 2025-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0011_major_grad_in_state_max_tuition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='GraduationRate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='university',
            name='TotalGradStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='university',
            name='TotalUndergradStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='university',
            name='aboutText',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
