# Generated by Django 4.2.16 on 2025-02-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0013_universityrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universityreview',
            unique_together={('username', 'university')},
        ),
    ]
