# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSubmitUniversityRequest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    # Wait until the page has loaded
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.TAG_NAME, "body"))
    )
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_submitUniversityRequest(self):
    self.driver.get("http://127.0.0.1:8000/")
    #self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.ID, "filter-dropdown").click()
    dropdown = self.driver.find_element(By.ID, "filter-dropdown")
    dropdown.find_element(By.XPATH, "//option[. = 'School']").click()
    self.driver.find_element(By.ID, "school-option").click()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("DoesNotExistU")
    self.driver.find_element(By.CSS_SELECTOR, ".fas").click()
    self.driver.find_element(By.LINK_TEXT, "Request University").click()
    self.driver.find_element(By.ID, "request_text").click()
    self.driver.find_element(By.ID, "request_text").send_keys("DoesNotExistU")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
