# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestclickLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    # Wait until the page has loaded
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.TAG_NAME, "body"))
    )
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testclickLogIn(self):
    self.driver.get("http://127.0.0.1:8000/")
    #self.driver.set_window_size(1908, 2036)
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.ID, "search-query").click()
    dropdown = self.driver.find_element(By.ID, "search-query")
    dropdown.find_element(By.XPATH, "//option[. = 'Engineering and Technology']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.LINK_TEXT, "MercuryU").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
  
