# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchwithnothing():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchwithnothing(self):
    self.driver.get("https://majorhelp.onrender.com/")
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".search-container > .filter-label")
    assert len(elements) > 0
  
