# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcontactandabout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcontactandabout(self):
    # Test name: test_contact_and_about
    # Step # | name | target | value
    # 1 | open | https://majorhelp.onrender.com/ | 
    self.driver.get("https://majorhelp.onrender.com/")
    time.sleep(2)
    # 2 | setWindowSize | 975x1032 | 
    self.driver.set_window_size(975, 1032)
    # 3 | click | linkText=About | 
    self.driver.find_element(By.LINK_TEXT, "About").click()
    time.sleep(2)
    # 4 | click | linkText=Contact | 
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    time.sleep(2)
    # 5 | click | linkText=MajorHelp | 
    self.driver.find_element(By.LINK_TEXT, "MajorHelp").click()
    time.sleep(2)
    # 6 | click | linkText=Log in | 
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    time.sleep(2)
    # 7 | close |  | 
    self.driver.close()
  
