# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcontactandabout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    # Wait until the page has loaded
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.TAG_NAME, "body"))
    )
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcontactandabout(self):
    # Test name: test_contact_and_about
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/ | 
    self.driver.get("http://127.0.0.1:8000/")
    time.sleep(2)
    # 2 | click | linkText=Search | 
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    time.sleep(2)
    # 3 | click | linkText=Tuition Calculator | 
    self.driver.find_element(By.LINK_TEXT, "Tuition Calculator").click()
    time.sleep(2)
    # 4 | click | linkText=College Map | 
    self.driver.find_element(By.LINK_TEXT, "College Map").click()
    time.sleep(2)
    # 5 | click | linkText=About | 
    self.driver.find_element(By.LINK_TEXT, "About").click()
    time.sleep(2)
    # 6 | click | linkText=Contact | 
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    time.sleep(2)
    # 5 | close |  | 
    self.driver.close()
  
